name: Deploy Cloud Functions

on:
  push:
    branches: ["main"]
    paths:
      - 'functions/**' # Only deploy if functions code changes
      - '.github/workflows/deploy-functions.yml'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: 'read'
  id-token: 'write'  # 這行最重要，用來換取 GCP 的 Token

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: weatherProxy
          runtime: nodejs20
          region: us-central1 # Update as needed
          source_dir: ./functions
          entry_point: weatherProxy
          ingress_settings: ALLOW_ALL
          https_trigger_security_level: secure_always
          max_instances: 1
          service_account_email: ${{ secrets.FUNCTION_BUILD_SERVICE_ACCOUNT }}
          timeout: 300
          env_vars: DEPLOYED_VIA=github-actions
